### ISSUE TITLE
Tab auto-fill names

### ISSUE THREAD

**Issue by Gaurav99** [TorchSpigot/Torch#100]
When you partially type in someone's username and hit "tab", generally it auto-fills their name or gives you options if they're multiple.  However, ever since we switched to torch, this no longer works in **chat messages** -- it works fine with commands.

Thanks!

**Comment by MrPowerGamerBR** [comment]
Can confirm, TAB complete is only working in commands.

No error seems to be thrown when trying to TAB complete in chat.

**Comment by Gaurav99** [comment]
We're on the latest build; bug seems to have resurfaced

**Comment by SotrForgotten** [comment]
@Gaurav99 but it works
http://imgur.com/a/HurT2

**Comment by MrPowerGamerBR** [comment]
@Gaurav99 @SotrForgotten I'm able to TAB complete player's name just fine.

![http://i.imgur.com/Xg6kY1M.png](http://i.imgur.com/Xg6kY1M.png)

**Comment by Gaurav99** [comment]
We updated the jar on the wrong dedi lmao.  Sorry about that
