### ISSUE TITLE
Players invisible on join (Random I think)

### ISSUE THREAD

**Issue by cloakfox** [TorchSpigot/Torch#103]
http://imgur.com/a/zzRYJ

No errors in console, and im not using any vanish plugins.
Was able to "fix" the issue by relogging the cloakfox account.
Relogging my alt "Knight_hawke" didn't work.

Using latest version of Torch.

**Comment by mat41997** [comment]
i have this same bug on my server

my timings
https://timings.aikar.co/?id=c2d2dd26b51d4e9ead460011883672f8

**Comment by SotrForgotten** [comment]
Try latest build, reopen if it still occurring.
