### ISSUE TITLE
Main Thread Hang: BlockMushroom

### ISSUE THREAD

**Issue by Joannou1** [TorchSpigot/Torch#108]
Hey, we were having some pretty nasty crashes as per https://github.com/PaperMC/Paper/issues/681
A friend suggested we give Torch a try, and saw that you had pushed some serious updates to the chunk/block system literally 5 minutes ago.

Gave that version a try just now, however the server hangs and crashes immediately when a player joins.
https://hastebin.com/ipefaviqiy.md

Also LibsDisguises doesn't load; https://hastebin.com/lehofimepo.vbs

**Comment by aFergydanny** [comment]
similar issue except soil block https://pastebin.com/BhRTKJqm

**Comment by SotrForgotten** [comment]
Try latest build

**Comment by Joannou1** [comment]
yeah seems all fixed.
