### ISSUE TITLE
Dies after a while

### ISSUE THREAD

**Issue by aFergydanny** [TorchSpigot/Torch#110]
Server just dies after a while. Crash : https://pastebin.com/Vr0GLiwc . 

~~also irongolems stop burning if their feet touch water even when their body is in lava (vanilla: https://i.gyazo.com/78b3f4387d4b532a6b8518aa55f050d4.png torch: https://i.gyazo.com/1025aaabdfa849752d10710d0f56d9d5.png) 
this technique is used by many to farm iron golems~~ the burning is fixed in latest, I will keep you posted on the crashes

**Comment by Joannou1** [comment]
Same, here's an assortment of crashes:

https://hastebin.com/udivasavah.md

**Comment by SotrForgotten** [comment]
It still occur in latest?

**Comment by aFergydanny** [comment]
hasn't crashed since I updated and iron golems burn proprely now
