### ISSUE TITLE
Might be an issue with Torch

### ISSUE THREAD

**Issue by mat41997** [TorchSpigot/Torch#112]
https://github.com/Minecrell/ServerListPlus/issues/158#issuecomment-302926317

**Comment by Yive** [comment]
Unable to reproduce on version af1cc2a even after restarting a few times with the following plugins:
[ServerListPlus 3.4.8-SNAPSHOT](https://ci.minecrell.net/job/ServerListPlus/410/)
[ProtocolSupport 4.26.dev](https://build.true-games.org/job/ProtocolSupport/54/)
[ProtocolLib 4.2.1](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.2.1)

**Comment by mat41997** [comment]
i use custom start command
```
screen -S mc -U -m java -server -Xms128M -Xmx3200M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=4 -XX:+AggressiveOpts -XX:UseSSE=3 -XX:SurvivorRatio=16 -XX:+UseCompressedOops -Xnoclassgc -XX:-UseFastEmptyMethods -XX:-UseFastAccessorMethods -XX:+UnlockExperimentalVMOptions -jar Torchpowered-1.11.2.jar
```

i still have this bug in af1cc2a
![2017-05-22_01 02 04](https://cloud.githubusercontent.com/assets/5884000/26288098/6cd2d61a-3e8a-11e7-8cd2-e9488f7c43e5.png)

tested on topplay.pl

**Comment by Yive** [comment]
Only difference is that you're running ServerListPlus 3.4.7. Maybe try & use 3.4.8 to see if that fixes the issue.
I tested with pretty much the same startup script minus -server since that's included in newer versions of Java.

**Comment by mat41997** [comment]
no, slp 3.4.8 not fix that bug

**Comment by mat41997** [comment]
no, i don't can reproduct this bug on my local pc : P
