### ISSUE TITLE
How to download

### ISSUE THREAD

**Issue by jordanwilliams1** [TorchSpigot/Torch#117]
Trying to build on a freash install of ubuntu server but keep getting this error:
https://i.gyazo.com/71da6488972907056e872007b6d46496.png

I've gotten this error on ubuntu and now on windows using git? How I fix

**Comment by SotrForgotten** [comment]
Install Maven first, or download directly (see readme)

**Comment by mat41997** [comment]
try this
https://yivesmirror.com/downloads/torch
