### ISSUE TITLE
Whitelist指令格式错误会出现报错

### ISSUE THREAD

**Issue by CBM1014** [TorchSpigot/Torch#118]
RT
http://oqpu2omvh.bkt.clouddn.com/17-5-29/54296382.jpg
http://oqpu2omvh.bkt.clouddn.com/17-5-29/46908020.jpg
使用的指令分别为

> whitelist add  1 (add与1间有两个空格)
> whitelist remove  1 (remove与1间有两个空格)
#  git-Torch-"7efabb5"

**Comment by SotrForgotten** [comment]
你输两个空格干嘛

**Comment by CBM1014** [comment]
噗噗噗，按说应该提示格式错误啊
比如ban加两个空格就会提示格式错误而不会报错_(:зゝ∠)_

**Comment by SotrForgotten** [comment]
吼吧

**Comment by CBM1014** [comment]
吼吧_(:зゝ∠)_
很迷的问题233333
