### ISSUE TITLE
Bans do not work

### ISSUE THREAD

**Issue by nikehin** [TorchSpigot/Torch#119]
Timings: https://timings.aikar.co/?id=177d4975519f4668a91ed1f25114f709
Console: https://pastebin.com/KF71H1eP
Server: 7efabb5

I use `online-mode: true` with modified autorization

**Comment by nikehin** [comment]
Again..
Server: ce767f9
Console: https://pastebin.com/h3SW29XM

**Comment by SotrForgotten** [comment]
well... it's easy to fix(we removed an override method by mistake) but since we updated the related mirror to 1.12, the version became uncompileable

**Comment by SotrForgotten** [comment]
Try build257(circleci)
