### ISSUE TITLE
Compatibility issue with MVdWPlaceholderAPI plugin

### ISSUE THREAD

**Issue by Gaurav99** [TorchSpigot/Torch#121]
On the latest version, on startup, this error occurs which prevents MVdWPlaceholderAPI from initializing: https://pastebin.com/6VNzp55f

The exact same server with the same plugins and whatnot on an older version (http://i.imgur.com/p6iVvRh.png) does not have this issue.  Something must have been recently changed to cause this.

**Comment by SotrForgotten** [comment]
Can't reproduce
