### ISSUE TITLE
Players cannot walk

### ISSUE THREAD

**Issue by enly1337** [TorchSpigot/Torch#122]
Players cannot walk and turn their heads. 
Happens unexpectedly and incomprehensibly when.

**Comment by enly1337** [comment]
Video: http://rgho.st/private/65xTkWxxy/63283c045e514eef58f7c952cdead781

**Comment by enly1337** [comment]
If u want watch video without downloading: https://yadi.sk/i/FnARUUqb3JmJdu

**Comment by mat41997** [comment]
timings
/timings on
/timings paste

actualize protocolsupport
https://build.true-games.org/job/ProtocolSupport/

use command:
/speed 1

install script
```
on join:
	reset walk speed of player
	stop
```

**Comment by mat41997** [comment]
https://github.com/ProtocolSupport/ProtocolSupport/issues/485

**Comment by enly1337** [comment]
Its not help.

**Comment by Dimatert9** [comment]
Ну видно же что какойто плагин отменяет PlayerMoveEvent, удаляй плагины по одному, как в старые добрые времена))

**Comment by enly1337** [comment]
В том то и проблема, что невозможно узнать, т.к. ошибка как-то странно появляется через раз.

**Comment by SotrForgotten** [comment]
Should be fixed now
