### ISSUE TITLE
Random error.

### ISSUE THREAD

**Issue by DuckCraftPvP** [TorchSpigot/Torch#123]
Hi, I found a error that only happens with TorchSpigot.

https://hastebin.com/atoherigub.md

**Comment by mat41997** [comment]
try actualize ProtocolLib
http://ci.dmulloy2.net/job/ProtocolLib/

**Comment by SotrForgotten** [comment]
What plugins are you using?

**Comment by DuckCraftPvP** [comment]
I tried adding Actualized and torch spigot.

I am using essentials protocollib protocolsupport and viaversion.

**Comment by SotrForgotten** [comment]
Try to update SpigotLib plugin

**Comment by DuckCraftPvP** [comment]
ok

**Comment by mat41997** [comment]
remove viaversion plugin and send your timings
/timings on
/timings paste
