### ISSUE TITLE
BKCommonLib

### ISSUE THREAD

**Issue by nikehin** [TorchSpigot/Torch#124]
BKCommonLib start with an error and crash after 60b40a5 - 8cae97d commits.
Error: https://pastebin.com/pXet7QBw

But it works on 7efabb5

**Comment by nikehin** [comment]
New crash report: https://pastebin.com/6uWqTn5T
Log: https://pastebin.com/eYPgFzCN

**Comment by SotrForgotten** [comment]
I know that, should fixed now.

**Comment by nikehin** [comment]
BKCommonLib now have full compatibility with PaperSpigot (https://github.com/bergerhealer/BKCommonLib/commit/9f1c3692a169204b971a0790d7ab1c6287cb5702).
I modified PaperSpigotServer.java to be compatible with TorchSpigot: https://pastebin.com/4wkQTCEG
Without modification: https://pastebin.com/NuZPBVy4

Log: https://pastebin.com/dBjEyFQA

**Comment by mat41997** [comment]
try this
https://www.spigotmc.org/resources/bkcommonlib.39590/
