### ISSUE TITLE
1.12 update?

### ISSUE THREAD

**Issue by Fonzee9** [TorchSpigot/Torch#130]

**Comment by mat41997** [comment]
good question, i aproved

Can we know the approximate date of implementation

**Comment by jordanwilliams1** [comment]
^

**Comment by Fonzee9** [comment]
8 days later

**Comment by DuckCraftPvP** [comment]
asap plox

**Comment by mattboy9921** [comment]
Really looking forward to 1.12 support.

**Comment by DuckCraftPvP** [comment]
ikr

**Comment by mattboy9921** [comment]
Any news on the 1.12 update?

**Comment by Fonzee9** [comment]
??

**Comment by mattboy9921** [comment]
Honestly, if there were any way I could help, I would but I honestly don't understand how all of this stuff works. I'm only familiar with low level Bukkit/Spigot plugins and such...

**Comment by mattboy9921** [comment]
It's been like a month without development, is this project going to make a comeback?

**Comment by jordanwilliams1** [comment]
tbh the difference between paper/torch is null. Torch would be great if mobs/ticks/hoppers were muti threaded which prorably will never happen 😢

**Comment by gpugeek** [comment]
where da memes @

**Comment by Vlvxingze** [comment]
Since most of China is version 1.8 of the server, I will give priority to the development of 1.8 of torch, 1.12 may not have, or slow forward

**Comment by mattboy9921** [comment]
Sorry to hear that, hopefully we will get a working 1.12 version at some point to test with. I'd love to see this kind of project take off as it would really change how Minecraft servers run. Thanks again for your work!
