### ISSUE TITLE
Multi-threading computing

### ISSUE THREAD

**Issue by jordanwilliams1** [TorchSpigot/Torch#131]
"Multi-threading computing" What parts of torch are Multi-Threaded? I Tested it will hoppers and there seems no difference. What is actually Multi-threaded about torch? I've seen timings from people from torch and the server load seems around the same as paper.

**Comment by DaemonBeel** [comment]
我是一个翻译。DifferentCraft 的主人（Jordanwillians1）请我来翻译他的问题。你们说火苣是多线程计算（multithreading computing）。那些火苣的部分
是“多线程计算”？ 我做了一些实验，我根本没有看到任何区别。我看到其他人的 Minecraft服务器，也没看到什么区别。

**Comment by SotrForgotten** [comment]
Torch has not finished yet and there are many things not implement, safety is first when we being "multithreading" and we also need to keeping compatible with plugins so there's little things are multithreaded(mostly in data saving), on the otherside, Torch also did regular optimizations just like Paper but they may not having an obviously improvement on server load.
Translation is needn't, but I'm doubt whether you can understand me :/

**Comment by DaemonBeel** [comment]
Okay, I understand English perfectly fine. So what's the estimated time for when will torch be completed? I'm a bit eager to test it out myself.
