### ISSUE TITLE
No finding some Torch features in 1.11.2_rc0.2

### ISSUE THREAD

**Issue by hilaolu** [TorchSpigot/Torch#133]
Dear staff:
I come from this post:http://www.mcbbs.net/forum.php?mod=viewthread&tid=610636.
I notice that some of the configure files that noticed in the post,like taco.yml & migot.yml, haven't been created before the server initialization.Also,the gc command /tgc isn't available in the version 1.11.2.
If I should create them by myself?
There 's another external problem.Though I am using the latest version 1.11.2_rc0.2,it will still notice me that the version is out of date...
By the way the server's performance is great.Thanks to you all for the hard work.Hoping for the better version : )

**Comment by SotrForgotten** [comment]
The thread was outdated, the features were removed
