### ISSUE TITLE
This project still going?

### ISSUE THREAD

**Issue by TheMasteredPanda** [TorchSpigot/Torch#136]
Is this repo still being maintained? And if it isn't, can the most recent revision of TorchSpigot be open source? I'd like to continue TorchSpigot if nobody else will.

**Comment by mattboy9921** [comment]
Issue #130 details the current state of the project. Basically said since most of China still uses 1.8, that will take development priority and 1.12 development will be slow, if any at all.

**Comment by TheMasteredPanda** [comment]
Alright. I've taken a copy of the most up to date revision so I can continue the project for the servers I am contracted to.

Thanks a bunch Matty!

**Comment by mat41997** [comment]
https://github.com/TorchSpigot/Torch/network

**Comment by mattboy9921** [comment]
Awesome! Glad to see continued development. I will head over there. If there's anything I can do to help, lemme know :D

**Comment by Vlvxingze** [comment]
yes going now
