### ISSUE TITLE
Are you sure using LightRNG is a good way to improve performance?

### ISSUE THREAD

**Issue by MrPowerGamerBR** [TorchSpigot/Torch#27]
Yeah, I know the "change shared Random to LightRNG" was a code I made for DreamSpigotPlus (my 1.7.10 server fork) but are you sure it does improve performance? I never done huge testing but... I think using SplittableRandom instead of Random (or LightRNG) would be a better choice. :)

**Comment by SotrForgotten** [comment]
tested, it's even faster than SplittableRandom, thanks.

**Comment by MrPowerGamerBR** [comment]
@SotrForgotten really? Wow, I didn't know my nooby patch would be useful to someone else project :)

(Also, can I backport some Torch patches to my 1.7.10 fork?)

**Comment by SotrForgotten** [comment]
@MrPowerGamerBR Sure :)  but the patches is a little bit mess..

**Comment by MrPowerGamerBR** [comment]
@SotrForgotten here's a little idea I had:

Why don't you change all "new Random()" to an static LightRandom? I done that on my 1.7.10 fork and it worked without any issues.

**Comment by MrPowerGamerBR** [comment]
@SotrForgotten 
```
package com.mrpowergamerbr.parappatown.utils;

public class LightStatic {
	public static LightRandom random = new LightRandom();
}
```
Then replace every ```new Random();``` with ```LightStatic.random;```

Maybe will affect the randomness of some things, but I think players won't notice it.

**Comment by MrPowerGamerBR** [comment]
@SotrForgotten ok, now the last thing I will ask, I promise :)

Are you going to backport those patches to Torch 1.8? I finally updated from 1.7.10 to 1.8.8 and now I'm using Torch 1.8, so I'm asking this question because it would be good if you backported more optimizations to 1.8.8 :+1:

**Comment by SotrForgotten** [comment]
@MrPowerGamerBR If I have time, I will do this..

**Comment by MrPowerGamerBR** [comment]
If I could compile Paper 1.8.8, I would port some of the patches...

However my computer doesn't want to compile it. (It says it wasn't
successful applying the patches due to invalid or lacking sha1)

Em 16 de ago de 2016 00:48, "Sotr" <notifications@github.com> escreveu:

**Comment by SotrForgotten** [comment]
@MrPowerGamerBR Try tacospigot?

**Comment by MrPowerGamerBR** [comment]
Already tried, they all have the same error.

This is because of the AutoCRLF but even after disabling/enabling that, the
same error happens.

Em 16 de ago de 2016 06:58, "Sotr" <notifications@github.com> escreveu:

**Comment by MrPowerGamerBR** [comment]
@SotrForgotten what do you use to compile Torch?

Git Bash (Windows), Cygwin (Windows) or Bash on Windows (Windows 10)? Or do you use a Linux OS?

**Comment by SotrForgotten** [comment]
@MrPowerGamerBR Git Bash (Windows).

**Comment by MrPowerGamerBR** [comment]
Huh, I also use Git Bash and it fails to compile Paper/TacoSpigot/Torch
(fails on the applyPatches.sh)

I think it fails to decompile, because it only decompiles some classes from
the 1.8.8.jar.

Em 16 de ago de 2016 22:23, "Sotr" <notifications@github.com> escreveu:

**Comment by MrPowerGamerBR** [comment]
@SotrForgotten (I already fixed the Git issue, on Windows the jdk/bin path isn't added by default, causing an error with the jar command)
