### ISSUE TITLE
关于更新

### ISSUE THREAD

**Issue by ningwang747** [TorchSpigot/Torch#30]
请更新至1.10

**Comment by SotrForgotten** [comment]
在1.9稳定之前，暂不打算更新1.10

**Comment by ningwang747** [comment]
不是已经Release了么(我的意思是先放出1.10的测试版)

**Comment by SotrForgotten** [comment]
可是1.9的版本问题还是很大（虽然已经release，而且暂时没精力做1.10（懒

**Comment by ningwang747** [comment]
出了1.10帮忙Close一下

**Comment by pspupsp** [comment]
我觉得可以出一个1.10.2-Beta版，1.11都已经出快照了，是时候弄1.10了。。。。

**Comment by SotrForgotten** [comment]
在paper等端更新到1.10.2-final之前不会更新 @pspupsp

**Comment by ningwang747** [comment]
= =
