### ISSUE TITLE
官网文字

### ISSUE THREAD

**Issue by ningwang747** [TorchSpigot/Torch#35]
![28e90d0344d5af5bfd3a77c7ed70ce897ca8f8632569cb4dffe30a9c5c4d79d3](https://cloud.githubusercontent.com/assets/18260727/17733140/bb008642-64a7-11e6-95b4-63f376eb30a9.png)
这些字背景色或者字体颜色改1下

**Comment by SotrForgotten** [comment]
官网不是由我维护，而且有三个站都在不同的服务器上。。没错的话应该只有一个有问题

**Comment by ningwang747** [comment]
还是老话，修复完close
