### ISSUE TITLE
服务器崩溃报告

### ISSUE THREAD

**Issue by ningwang747** [TorchSpigot/Torch#37]
[crash-2016-08-18_07.44.21-server.txt](https://github.com/TorchSpigot/Torch/files/424793/crash-2016-08-18_07.44.21-server.txt)

**Comment by SotrForgotten** [comment]
尝试 R1.8.1-RC1放在Release candidate里。

**Comment by ningwang747** [comment]
那#36什么时候修复呢

**Comment by SotrForgotten** [comment]
@ningwang747 暂时无法修复

**Comment by ningwang747** [comment]
这个崩溃是什么引发的

**Comment by ningwang747** [comment]
还有1个问题,R1.8的实体1直不停转圈

**Comment by SotrForgotten** [comment]
@ningwang747 实体转圈已经修复，可以使用RC2
