### ISSUE TITLE
WE的时候周围方块有时候会亮起来

### ISSUE THREAD

**Issue by ningwang747** [TorchSpigot/Torch#39]
我确定是全密封
外面
![73fb064b30388efce691e42f053941c4](https://cloud.githubusercontent.com/assets/18260727/17829140/9eaf089c-66d7-11e6-8d61-fac0f80628e2.jpg)
里面
![0c690b6527fec2b1b108bc25565e0847](https://cloud.githubusercontent.com/assets/18260727/17829144/b198b494-66d7-11e6-9f3c-63ccb6010a47.jpg)

**Comment by SotrForgotten** [comment]
请尝试将在paper.yml里中的queue-light-updates项设置为false，建议提交到Paper

**Comment by ningwang747** [comment]
你能帮我提交吗，我英文语法不好
