### ISSUE TITLE
水不流(非静止的水(天然生成))

### ISSUE THREAD

**Issue by ningwang747** [TorchSpigot/Torch#44]
![c3179f46-7cf1-4bcb-91f3-ad93ee2f90c2](https://cloud.githubusercontent.com/assets/18260727/18024886/93514656-6c48-11e6-9949-8b9c2e153a27.png)

**Comment by SotrForgotten** [comment]
尝试最新版本

**Comment by ningwang747** [comment]
进入服务器时报错
