### ISSUE TITLE
java.lang.StackOverflowError: Exception ticking world

### ISSUE THREAD

**Issue by gabriel-mao** [TorchSpigot/Torch#63]
服务器直接挂掉了，1.9.4版本，有人碰到过么？跑了大概2天。
报错的log如下
[crash-2017-02-14_20.27.39-server.txt](https://github.com/TorchSpigot/Torch/files/775955/crash-2017-02-14_20.27.39-server.txt)

**Comment by ningwang747** [comment]
outdated version
