### ISSUE TITLE
i don't can download the latest torchspigot for pan.baidu.com

### ISSUE THREAD

**Issue by mat41997** [TorchSpigot/Torch#65]
i must use a vpn to connect this site and i can't download this file
![2017-04-05 21_12_56-torchspigot-target_ _ -](https://cloud.githubusercontent.com/assets/5884000/24722625/bb7578fa-1a44-11e7-99ee-903da2a6a628.png)

pls. upload to google drive or dropbox

**Comment by SotrForgotten** [comment]
You can download latest build from CircleCI now.
