### ISSUE TITLE
红石使用发现问题

### ISSUE THREAD

**Issue by CBM1014** [TorchSpigot/Torch#70]
1.在重生点附近常加载区块外[仅经过几次实验，范围不一定准确]，投掷器无法将物品送入容器，物品会被以item的形式发射出去。
2.部分玩家反映侦测器无法[或有几率不能]侦测西瓜生长。主要表现为用侦测器驱动的西瓜机瘫痪。

**Comment by Vlvxingze** [comment]
过期了
