### ISSUE TITLE
what is wrong

### ISSUE THREAD

**Issue by mat41997** [TorchSpigot/Torch#73]
Suddenly there appeared 3 lakes

ss
![2017-04-29_19 51 47](https://cloud.githubusercontent.com/assets/5884000/25557635/d2f9c77c-2d15-11e7-94d2-df4f6e9188ff.png)
![2017-04-29_19 51 57](https://cloud.githubusercontent.com/assets/5884000/25557636/d2fabc36-2d15-11e7-8586-95ef3eaee59d.png)
![2017-04-29_19 55 18](https://cloud.githubusercontent.com/assets/5884000/25557637/d2fb5f38-2d15-11e7-9ac3-9e9fb5240256.png)

timings
https://timings.aikar.co/?id=a6f880846aed4627a0580113c0b6b40e

**Comment by mat41997** [comment]
Plague progresses
![2017-04-29_20 03 56](https://cloud.githubusercontent.com/assets/5884000/25557717/3fc626c4-2d17-11e7-860d-6bec3ff9e500.png)

**Comment by SotrForgotten** [comment]
The result of `atan2` in `TrigMath` is much different from `MathHelper` one, which may cause this issue.
Anyway, sorry for that.
