### ISSUE TITLE
Server stopped with error

### ISSUE THREAD

**Issue by Keksik9000** [TorchSpigot/Torch#81]
Sometimes server stops with that error:

https://pastebin.com/0AqLZRUA

Plugin list: https://pastebin.com/553VAa5d

I think it can be caused by ProtocolSupport. Can you check it?

**Comment by mat41997** [comment]
try use the latest torchspigot
https://circleci.com/gh/TorchSpigot/Torch/tree/master

and latest protocolsupport
https://build.true-games.org/job/ProtocolSupport/

pls. send your timings

use to this
/timings on
/timings paste

**Comment by SotrForgotten** [comment]
Try latest build.
