### ISSUE TITLE
官网错误

### ISSUE THREAD

**Issue by ningwang747** [TorchSpigot/Torch#82]
![1](https://cloud.githubusercontent.com/assets/18260727/25772557/bdb1f49e-32a0-11e7-8a9a-391652588fb8.png)
![2](https://cloud.githubusercontent.com/assets/18260727/25772558/bdff0126-32a0-11e7-97cb-982adff11bab.png)

**Comment by SotrForgotten** [comment]
@KiwiSAMA

**Comment by Vlvxingze** [comment]
官网没了
看看这个
https://www.relatev.com/forum.php?mod=viewthread&tid=45
