### ISSUE TITLE
在使用在线验证的Bungeecord下添加白名单依然会本地生成UUID # git-Torch-"b9d0733"

### ISSUE THREAD

**Issue by CBM1014** [TorchSpigot/Torch#86]
RT
添加已经注册过的ID依然会本地生成UUID,导致更新此构建后被添加白名单的玩家无法进入服务器。
区别于Issues #79 ，这次的问题是出在已经注册的ID上的。
# git-Torch-"b9d0733"

**Comment by SotrForgotten** [comment]
忘记检查bungee正版验证的情况，稍后修复。
（todo 正版uuid未获取到的情况也没有检查）
另外留意打开paper.yml中的bungee-online-mode
