### ISSUE TITLE
fastcraft+ not work

### ISSUE THREAD

**Issue by mat41997** [TorchSpigot/Torch#87]
ss
![2017-05-09_21 47 19](https://cloud.githubusercontent.com/assets/5884000/25869589/2052f5dc-3501-11e7-83ce-a18141d6a39a.png)

fc+
https://www.spigotmc.org/resources/fastcraft.20544/

timings
https://timings.aikar.co/?id=8abcf772070e46c185004e8ed70d1fcf

only work for used that command
/fc craft

**Comment by Fonzee9** [comment]
I have fastcraft and it works great with Torchspigot

**Comment by mat41997** [comment]
you can tested on this server
topplay.pl

**Comment by SotrForgotten** [comment]
Can't reproduce, it works.
http://imgur.com/a/u0S9K
