### ISSUE TITLE
Torch breaks op permissions.

### ISSUE THREAD

**Issue by Fonzee9** [TorchSpigot/Torch#90]
Okay so i have permissions with Paper since i am opped so all commands then when i switch to Torch some plugins don't give me perms anymore.

**Comment by Fonzee9** [comment]
Another problem with this is one of the plugins i use don't have perms so the only way to access it is with OP so i am unable to access it.

**Comment by mat41997** [comment]
try use alternative permission plugin

check luckperms
https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/

**Comment by SotrForgotten** [comment]
Running in bungee online mode? need more info

**Comment by Fonzee9** [comment]
Running a normal server using GroupManager heres an idea of whats suppose to happen. The plugin is suppose to work with the commands using admaps for this and as you see Torch denys it while paper allows use of the command.

Paper: What suppose to happen.

![2017-05-12_12 09 49](https://cloud.githubusercontent.com/assets/21323258/26006867/1e99fc42-370c-11e7-9fe1-a12f219107db.png)



Torch: Blocks command from being used from being opped and also i have owner rank on my server.
![ok](https://cloud.githubusercontent.com/assets/21323258/26006871/2199d30e-370c-11e7-8262-760b68b99c27.png)

**Comment by Fonzee9** [comment]
As you see in that picture Torch blocks me access to that command but in Paper i can use it

**Comment by SotrForgotten** [comment]
Try latest build.

**Comment by Fonzee9** [comment]
I am on build 141 which is latest

**Comment by Fonzee9** [comment]
Okay i see you published build 142 ill give it a try

**Comment by Fonzee9** [comment]
Your update crashed my server and gave me an error: https://pastebin.com/nNEfKLzU

**Comment by Fonzee9** [comment]
No the update didn't fix the problem

**Comment by SotrForgotten** [comment]
Try to delete ops.json/usercache.json and generate new one (UUID may has changed)

**Comment by Fonzee9** [comment]
I did same problem

**Comment by SotrForgotten** [comment]
Tested with GroupManager/AdMaps but can't reproduce the issue, try re-add permissions (like /manuaddp ownerID *)
