### ISSUE TITLE
stopTiming called async & stack trace Issue

### ISSUE THREAD

**Issue by Jnxd1** [TorchSpigot/Torch#92]
I'm having this error spammed from several plugins.
[https://hastebin.com/uwaveqivox.vbs](url)
When i contacted the dev of Merged Mobs he said to report it here.
And this one here which im not sure what to make of it
[https://hastebin.com/cusifinura.md](url)
Thanks

**Comment by SotrForgotten** [comment]
Torch1.8 is not supported, better update to 1.11.2
