### ISSUE TITLE
白名单工作不正常

### ISSUE THREAD

**Issue by CBM1014** [TorchSpigot/Torch#95]
RT
已经检查过whitelist.json中记录的UUID与name正确
玩家登陆使用的UUID与whitelist.json中记录的UUID匹配，但依然无法进入服务器。
例外的是，**在服务器开启以后新添加白名单的玩家可以正常进入服务器，但服务器重启后无法再进入。**

http://i4.buimg.com/588926/a00a8b9e392f992e.png
http://i1.piimg.com/588926/a86200b3016e5a4f.png
http://i4.buimg.com/588926/a3e0d34e20e8730a.png

# git-Torch-"8ee61d7"

**Comment by SotrForgotten** [comment]
눈_눈

**Comment by CBM1014** [comment]
依然工作不正常
# git-Torch-"94fd140"

**Comment by SotrForgotten** [comment]
db04a12

**Comment by CBM1014** [comment]
http://oqpu2omvh.bkt.clouddn.com/17-5-29/62668494.jpg
# git-Torch-"7efabb5"
