### ISSUE TITLE
Server crashes randomly on login

### ISSUE THREAD

**Issue by MrPowerGamerBR** [TorchSpigot/Torch#97]
https://gist.github.com/MrPowerGamerBR/3f15991d99050268b2586a76c23ebaca

I'm not sure how to reproduce this issue yet, but it seems the server randomly crashes when logging in.

However I'm not using the latest build yet, if this issue stops happening in the latest build, then I will close this issue.

And, if I find how to reproduce it, I will add a step by step tutorial on how to reproduce this.

**Comment by MrPowerGamerBR** [comment]
I think it is due to the WeakHashMap being accessed in a non thread safe way.

When a WeakHashMap is edited in a non thread safe way while another thread is already editing the WeakHashMap, Java, instead of throwing a ConcurrentModificationException, it only freezes the thread.

What I recommend is replacing that WeakHashMap with Guava's Cache (Guava is concurrent while WeakHashMap isn't)

**Comment by MrPowerGamerBR** [comment]
Yep, I think this is the issue, something is accessing that WeakHashMap in a different thread while another thread is editing the WeakHashMap.

When a WeakHashMap is edited in a non thread safe manner, the WeakHashMap get stuck in a infinite loop (instead of throwing an exception like how other Collections does)

I had this issue before in another software I was editing (someone was using WeakHashMaps as cache, WeakHashMap shouldn't be used for cache!) where the server froze due to something editing the cache WeakHashMap while another thread was already editing it.

(Here's the stack trace I had in another software when something was editing the WeakHashMap in a non thread safe way)
![http://i.imgur.com/XlPwQ7u.png](http://i.imgur.com/XlPwQ7u.png)

**Comment by SotrForgotten** [comment]
The Bukkit plugin manager is not safe, cause the issue. I'll modify the API part later.
