### ISSUE TITLE
Server crash when getting the user's UUID

### ISSUE THREAD

**Issue by MrPowerGamerBR** [TorchSpigot/Torch#98]
https://gist.github.com/MrPowerGamerBR/53a07d3fd58e83eee4c649efe95e1e1f

Using latest Torch build.

Maybe related to #97? This happened after changing an Citizens NPC skin (but this doesn't happen every time someone changes the NPC skin)

**Comment by mat41997** [comment]
any timings?
/timings on
/timings paste

**Comment by MrPowerGamerBR** [comment]
@mat41997 nope, I didn't do a Timings report yet.

But reproducing this issue is easy, just keep creating Citizens' NPCs (or just keep changing an NPC skin) until the server crashes.

The server that this crash happened didn't even have a lot of "wow so many plugins", it is just a small server that I was using for building my new server and it only had 3 players online when it crashed.

Anyway, if I'm able to, I will post a Timings report.

**Comment by mat41997** [comment]
you are used the beta version of citizens plugin ( build 1474 )

try latest stabile build ( build 1463 )
https://dev.bukkit.org/projects/citizens/files/2360848

**Comment by MrPowerGamerBR** [comment]
@mat41997 I will try using the stable build later.

However, this same development build doesn't crash in Paper when editing/creating Citizens NPCs.
